# This is a combination of 2 commits. # This is the 1st commit message:
Reorganize namespaces and fix tests

Update component versions via the CLI

Create tags in components

Send component name and version in user agent

Add README files

Fix CLI

Add split to travis

Test datastore release

Compile splitsh

Reintroduce full split process

Release patches

# This is the commit message #2:

Run split in each build matrix

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,43 +1,27 @@
 language: php
-
 sudo: required
 dist: trusty
 
 matrix:
-    include:
-        - php: 5.5.38
-        - php: 5.6.25
-        - php: 7.0
-        - php: 7.1
-        - php: hhvm
-         group: edge
-    fast_finish: true
+  include:
+  - php: 5.5.38
+  - php: 5.6.25
+  - php: 7.0
+  - php: 7.1
+  - php: hhvm
+    group: edge
+  fast_finish: true
 
 before_script:
-   - pecl install grpc || echo 'Failed to install grpc'
-   - composer install
+  - pecl install grpc || echo 'Failed to install grpc'
+  - composer install
 
 script:
-    - ./dev/sh/tests
-    - vendor/bin/phpcs --standard=./phpcs-ruleset.xml
-    - ./dev/sh/build-docs
-    - curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
-
-after_script:
-    - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
+  - ./dev/sh/tests
+  - vendor/bin/phpcs --standard=./phpcs-ruleset.xml
+  - ./dev/sh/build-docs
 
 after_success:
-    - bash <(curl -s https://codecov.io/bash)
-    - python travis_after_all.py https://api.travis-ci.com
-    - export $(cat .to_export_back)
-    - |
-      if [ "$BUILD_LEADER" = "YES" ]; then
-        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
-          ./dev/sh/push-docs
-          ./dev/sh/compile-splitsh
-          git fetch --unshallow
-          composer google-cloud split
-        else
-          echo "Some jobs failed"
-        fi
-      fi
+  - bash <(curl -s https://codecov.io/bash)
+  - ./dev/sh/push-docs
+  - ./dev/sh/trigger-split
